FROM openjdk:8-jre-slim

MAINTAINER nagarajulrpt@gmail.com
		
ARG JMETER_VERSION=5.0
		
RUN apt-get clean && \
	apt-get update && \
	apt-get -qy install \
	wget \
	telnet \
	iputils-ping \
	unzip
		
RUN   mkdir /jmeter \
	&& cd /jmeter/ \
	&& wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz \
	&& tar -xzf apache-jmeter-$JMETER_VERSION.tgz \
	&& rm apache-jmeter-$JMETER_VERSION.tgz
	
	#ADD jmeter-plugins/lib /jmeter/apache-jmeter-$JMETER_VERSION/lib
	
RUN /docker-java-home/jre/bin/keytool -genkey -keyalg RSA -alias rmi -keystore /jmeter/apache-jmeter-$JMETER_VERSION/bin/rmi_keystore.jks -dname "CN=rmi, OU=ERT, O=EPAM, L=Hyderabad, ST=Telangana, C=IN" -keypass changeit -storepass changeit -validity 365 -keysize 2048

ENV JMETER_HOME /jmeter/apache-jmeter-$JMETER_VERSION/
		
ENV PATH $JMETER_HOME/bin:$PATH

WORKDIR $JMETER_HOME/bin
