apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: jmeter-slave
  labels:
    jmeter_mode: slave
spec:
  replicas: 1 
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
      - name: jmeter-slave
        image: nagarajulrpt/openjdk_jmeter5.0_client:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 1099
        - containerPort: 60000
      nodeSelector:
        performance-testing: "true"        
