{
 "title": "JMeter Summary Report",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "app_name",
    "label": "Application Name",
    "query": "SHOW TAG VALUES FROM \"jmeter\" WITH KEY = \"application\""
   },
   { "name": "granularity", "label": "Granularity", "query": "10s,15s,30s,60s,5m,15m,30m,60m" }
  ]
 },
 "panels": [
  { "title": "Transaction Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transaction Summary",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": " select min(\"min\") as Min,LAST(\"avg\") as Avg, max(\"max\") as Max, count(\"count\")as Count, count(countError) as Error_Count,LAST(\"pct90.0\") as Perc_90,LAST(\"pct95.0\") as Perc_95,LAST(\"pct99.0\") as Perc_99 from jmeter where (application=~/^$app_name/ AND statut='ok') AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"count\")as Count, count(count) as Error_Count,LAST(\"avg\") as Avg,min(\"min\") as Min, max(\"max\") as Max, LAST(\"pct90.0\") as Perc_90,LAST(\"pct95.0\") as Perc_95,LAST(\"pct99.0\") as Perc_99 from jmeter WHERE (\"application\"=~/^$app_name$/ AND statut='ko' ) AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "User Load and Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Users",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"maxAT\") FROM \"jmeter\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$app_name$/)  AND $timeFilter GROUP BY time($granularity)  fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "No of Errors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"countError\") FROM \"jmeter\" WHERE (\"transaction\" = 'all' AND \"application\" =~ /^$app_name$/) AND $timeFilter  GROUP BY time($granularity) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg. Transaction Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"avg\" FROM \"jmeter\" WHERE (\"statut\" = 'ok' AND \"application\" =~ /^$app_name$/)  AND $timeFilter GROUP BY transaction",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Error Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"application\" =~ /^$app_name$/ AND \"responseCode\" !~ /^$/) AND $timeFilter GROUP BY \"transaction\",\"responseCode\",\"responseMessage\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(rb) from jmeter where(\"transaction\" = 'all' AND \"application\" =~ /^$app_name$/ AND \"statut\"='all') AND $timeFilter GROUP BY time($granularity) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}