apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    app: grafana
data:
  grafana.ini: |
    GF_AUTH_BASIC_ENABLED = "true"
    GF_USERS_ALLOW_ORG_CREATE = "true"
    GF_AUTH_ANONYMOUS_ENABLED = "true"
    GF_AUTH_ANONYMOUS_ORG_ROLE = Admin
    GF_SERVER_PROTOCOL = "http"
    GF_SERVER_HTTP_PORT = 3000
    GF_SERVER_DOMAIN = "jmeter-dashboards.com"
    GF_SERVER_ROOT_URL = http://jmeter-dashboards.com:3000
    
