apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  labels:
    app: influxdb
data:
  influxdb.conf: |
    [meta]
      dir = "/influxdb/meta"
    [data]
      dir = "/influxdb/data"
      engine = "tsm1"
      wal-dir = "/influxdb/wal"
    # Configure the graphite api
    [[graphite]]
    enabled = true
    bind-address = ":2003" # If not set, is actually set to bind-address.
    database = "jmeter"  # store graphite data in this database
    retention-policy = ""
    protocol = "tcp"
    batch-size = 5000
    batch-pending = 10
    batch-timeout = "1s"
    consistency-level = "one"
    separator = "."
    udp-read-buffer = 0
    templates = [
      "measurement.ProjectName.TestType.RunID.page.status.metric",
      "jmeter.*.*.*.test measurement.ProjectName.TestType.RunID.measurement.thread"  
    ]
